### ISSUE TITLE
копіювання стейту

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-28-React-user-list#1]
https://github.com/BohdanLuts/home-work-lesson-28-React-user-list/blob/be4417187fd051ec8eb011e6bfd8882ce5e301bf/src/components/UsersList/index.jsx#L63
- тут нема сенcу копіювати, оскільки при фільтрації і так створюжться новий масив, а не змінюється поточний, тобто достатньо:
```
const newUsers = users.filter((i) => i.id !== id);
```

**Comment by BohdanLuts** [comment]
Замінено
