### ISSUE TITLE
зайвий код

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-28-React-user-list#2]
https://github.com/BohdanLuts/home-work-lesson-28-React-user-list/blob/be4417187fd051ec8eb011e6bfd8882ce5e301bf/src/components/UsersList/index.jsx#L63
- цей і наступний рядки варто прибрати в результуючому коді

**Comment by BohdanLuts** [comment]
Без цих рядків не працює видалення користувачів. 
Мова йде про рядок 65? 

console.log("removeIndex", removeIndex);

**Comment by pecourses** [comment]
Так, 64 і 65. Як я бачу, в 64 просто перевіряється, дані під яким індексом відалялися, але змінна для самого видалення не використовується.

**Comment by BohdanLuts** [comment]
Згоден, виправив у наступному комміті
